### ISSUE TITLE
could not find function "parseAIRR"

### ISSUE THREAD

**Issue by kriegerm** [ncborcherding/scRepertoire#356]
I am trying to load in some contigs from a BD Rhapsody run, but keep getting the following error:

```r
contigs_dir <- c("/path/to/SeqRun1-TCR-ST_VDJ_Dominant_Contigs_AIRR.tsv", "th/to/SeqRun2-TCR-ST_VDJ_Dominant_Contigs_AIRR.tsv")
contig.list <- loadContigs(contigs_dir, format="BD")  

Error in `parseAIRR()`:
! could not find function "parseAIRR"
Backtrace:
 1. scRepertoire::loadContigs(contigs_dir, format = "BD")
``` 

Any help to solve would be greatly appreciated!

**Comment by ncborcherding** [comment]
Hey Madeline, 

Happy to help - strange error that you are calling for the internal function .parseBD with ```loadContigs(..., format="BD")```, but getting an error for an entirely different format. 

What version of scRepertoire are you using? 

Nick

**Comment by kriegerm** [comment]
Thanks for your quick reply :) I am using scRepertoire_1.12.0

If this helps, here are my outputs when I specify other formats:
```r
> contig.list <- loadContigs(contigs_dir, format="AIRR")        
Error in parseAIRR(df) : could not find function "parseAIRR"

> contig.list <- loadContigs(contigs_dir)        
Error in parse10x(df) : could not find function "parse10x"
```

**Comment by ncborcherding** [comment]
Hey Madeline,

There was a major expansion of ```loadContigs()``` to try to support the broadest number of formats in the newest version 2 of scRepertoire, so that is the origin of the error. If you want AIRR support, you can install the newest version of scRepertoire using: 

```
remotes::install_github("ncborcherding/scRepertoire")
```

Sorry for the confusion. 

Nick

**Comment by kriegerm** [comment]
Great, that worked! But I do have another issue popping up.

```r

S1 <- read.table("/path/to/S1_VDJ_Dominant_Contigs_AIRR.tsv", sep="\t", header=TRUE)
S2 <- read.table( "/path/to/S2_VDJ_Dominant_Contigs_AIRR.tsv"", sep="\t", header=TRUE)
contig_list <- list(S1, S2)
contig.list <- loadContigs(input = contig_list, format = "BD")

combined <- combineTCR(contig_list,samples = c("S1", "S2"),removeNA=TRUE)

<error/dplyr:::mutate_error>
Error in `mutate()`:
ℹ In argument: `TCR1 = ifelse(...)`.
Caused by error:
! object 'chain' not found
---
Backtrace:
     ▆
  1. ├─scRepertoire::combineTCR(...)
  2. │ └─scRepertoire:::.makeGenes(cellType = "T", out[[i]])
  3. │   └─... %>% ...
  4. ├─dplyr::mutate(...)
  5. ├─dplyr::mutate(...)
  6. ├─dplyr:::mutate.data.frame(...)
  7. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
  8. │   ├─base::withCallingHandlers(...)
  9. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 10. │     └─mask$eval_all_mutate(quo)
 11. │       └─dplyr (local) eval()
 12. ├─base::ifelse(...)
 13. └─chain %in% c("TRA", "TRG")
Run rlang::last_trace(drop = FALSE) to see 3 hidden frames.

```

**Comment by kriegerm** [comment]
More info (not sure if this helps diagnostically at all)

```r
contig.merged <- createHTOContigList(contig_list, merged_seruat_obj) #throws the same error whether or not group_by is invovled

Error in contig[contig$barcode %in% rownames(meta), ] : 
  incorrect number of dimensions
  
  > lapply(contig_list, dim)                                                      
[[1]]
[1] 23807    50

[[2]]
[1] 8934   50


```

**Comment by ncborcherding** [comment]
```
S1 <- read.table("/path/to/S1_VDJ_Dominant_Contigs_AIRR.tsv", sep="\t", header=TRUE)
S2 <- read.table( "/path/to/S2_VDJ_Dominant_Contigs_AIRR.tsv"", sep="\t", header=TRUE)
contig_list <- list(S1, S2)
contig.list <- loadContigs(input = contig_list, format = "BD")

combined <- combineTCR(contig_list,samples = c("S1", "S2"),removeNA=TRUE)
```

This all looks correct but the error suggests that the contigs are missing a header. Would you mind giving me the output of ```head(S1)``` just so I can see if the columns match the anticipated columns for parsing BD format? 

In terms of the createHTO issue - my guess is that the barcodes in the contigs do not match the barcodes in the Seurat object. This is actually a common issue because BD numbers cells with cell_id. 

Nick

**Comment by ncborcherding** [comment]
Hey Madeline, 

What is throwing things off here is a new column in the BD format called "cell_type_experimental". The ```loadContigs()``` function anticipates locus to be in column 2. There are probably downstream complications as well - the pull of wrong aa/nt sequences. 

Ironically, I just pushed a fix for this 2 days ago into the [dev branch](https://github.com/ncborcherding/scRepertoire/tree/dev) - I need to do a little more testing before I merge that into the master branch. 

For the createHTO problem - you will need to look how the processing of the seurat workflow changes the barcode ID. I am not sure if Seurat retains the numeric cell_id or adds _# or something like that for BD experiments. If you can give me an example (like head() of the first few columns of the meta data) - I'd be happy to point you. 

Nick

**Comment by kriegerm** [comment]
Ok, great! I'll just remove that "cell_type_experimental" column and give it a go. 

Here are the column names of the metadata:
```
 [1] "orig.ident"                               
 [2] "nCount_RNA"                               
 [3] "nFeature_RNA"                             
 [4] "Cell_Type_Experimental"                   
 [5] "Sample_Tag"                               
 [6] "Sample_Name"                              
 [7] "Total_VDJ_Read_Count"                     
 [8] "Total_VDJ_Molecule_Count"                 
 [9] "TCR_Alpha_Gamma_V_gene_Dominant"          
[10] "TCR_Alpha_Gamma_J_gene_Dominant"          
[11] "TCR_Alpha_Gamma_C_gene_Dominant"          
[12] "TCR_Alpha_Gamma_CDR3_Nucleotide_Dominant" 
[13] "TCR_Alpha_Gamma_CDR3_Translation_Dominant"
[14] "TCR_Alpha_Gamma_Read_Count"               
[15] "TCR_Alpha_Gamma_Molecule_Count"           
[16] "TCR_Beta_Delta_V_gene_Dominant"           
[17] "TCR_Beta_Delta_D_gene_Dominant"           
[18] "TCR_Beta_Delta_J_gene_Dominant"           
[19] "TCR_Beta_Delta_C_gene_Dominant"           
[20] "TCR_Beta_Delta_CDR3_Nucleotide_Dominant"  
[21] "TCR_Beta_Delta_CDR3_Translation_Dominant" 
[22] "TCR_Beta_Delta_Read_Count"                
[23] "TCR_Beta_Delta_Molecule_Count"            
[24] "TCR_Paired_Chains"                        
[25] "percent.mt"                               
[26] "S.Score"                                  
[27] "G2M.Score"                                
[28] "Phase"                                    
[29] "old.ident"                                
[30] "RNA_snn_res.0.8"                          
[31] "seurat_clusters"                          
[32] "tissue_source" 
``` 

Major thanks in being so helpful and responsive with these issues!

**Comment by kriegerm** [comment]
Update: Unfortunately, I removed the second column from my tsv file and re-ran the code, but am still getting the same error:

```
S1 <- read.table("/path/to/S1_VDJ_Dominant_Contigs_AIRR_edited.tsv", sep="\t", header=TRUE)
S2 <- read.table( "/path/to/S2_VDJ_Dominant_Contigs_AIRR_edited.tsv"", sep="\t", header=TRUE)
contig_list <- list(S1, S2)
contig.list <- loadContigs(input = contig_list, format = "BD")

combined <- combineTCR(contig_list,samples = c("S1", "S2"),removeNA=TRUE)

<error/dplyr:::mutate_error>
Error in `mutate()`:
ℹ In argument: `TCR1 = ifelse(...)`.
Caused by error:
! object 'chain' not found
``` 

For reference (same output as colnames(S1)):
```
colnames(S2)
 [1] "cell_id"                      "locus"                       
 [3] "sequence_id"                  "consensus_count"             
 [5] "duplicate_count"              "sequence"                    
 [7] "sequence_length"              "sequence_aa"                 
 [9] "sequence_aa_length"           "sequence_alignment"          
[11] "sequence_alignment_length"    "sequence_alignment_aa"       
[13] "sequence_alignment_aa_length" "germline_alignment"          
[15] "junction"                     "junction_aa"                 
[17] "productive"                   "rev_comp"                    
[19] "complete_vdj"                 "v_call"                      
[21] "v_support"                    "v_cigar"                     
[23] "v_sequence_start"             "v_sequence_end"              
[25] "d_call"                       "d_support"                   
[27] "d_cigar"                      "d_sequence_start"            
[29] "d_sequence_end"               "j_call"                      
[31] "j_support"                    "j_cigar"                     
[33] "j_sequence_start"             "j_sequence_end"              
[35] "c_call"                       "fwr1"                        
[37] "fwr1_aa"                      "fwr2"                        
[39] "fwr2_aa"                      "fwr3"                        
[41] "fwr3_aa"                      "fwr4"                        
[43] "fwr4_aa"                      "cdr1"                        
[45] "cdr1_aa"                      "cdr2"                        
[47] "cdr2_aa"                      "cdr3"                        
[49] "cdr3_aa"                     
```

**Comment by kriegerm** [comment]
Hi @ncborcherding , just checking in on this question. Thanks! :)

**Comment by ncborcherding** [comment]
Sorry I must have missed the update - the columns look correct. The parse/```loadContigs()``` functions as a whole are only interested in the following columns: 

```
c("cell_id","locus","v_call","d_call","j_call", "c_call", "cdr3","cdr3_aa","consensus_count", "productive")
```

It looks like you are all good there. I have been trying to get the new changes to ```loadContigs()``` tested more and pushed to the master branch (but have had a family thing come up). In the mean time, you could try installing the dev version (pre 2.0.3) and see if this solves the issue. 

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

Nick

**Comment by kriegerm** [comment]
Hi @ncborcherding  - hope things are well with you and your family! 

If you have a moment, I'm still struggling with the createHTOContigList function with my data. I got it to accept the contigs using combineTCR by editing some of the headers, which is great. But it still isn't happy with combining that data and my seurat object. I suppose it's because of the cell_id/barcode names being just numerical with the BD data, but would really appreciate any guidance on how to fix that. 

```r
contig_list <- list(S1, S2)
combined <- combineTCR(contig_list,samples = c("Type1", "Type2"), removeNA=TRUE)

sce_tcr <- createHTOContigList(combined, sce, group.by = "tissue_source")

Error in `contig[contig$barcode %in% rownames(meta), ]`:
! incorrect number of dimensions
``` 

Thanks again!

**Comment by ncborcherding** [comment]
Hey Madeline, 

You will need to run ```createHTOContigList()``` on the contigs before using ```combineTCR()```. 

Hope that helps,
Nick

**Comment by kriegerm** [comment]
Ok, I think I'm ALMOST there! I've gotten my contigs to combine and gotten graphical output from the following commands:

```r
my_list <- list(S1, S2)
contig.list <- loadContigs(input = my_list, format="BD")
combined.TCR<- combineTCR(contig.list,samples = c("S1", "S2"),removeNA=TRUE)

clonalQuant(combined.TCR, 
            cloneCall="strict", 
            chain = "both", 
            scale = TRUE)
         
clonalAbundance(combined.TCR, 
                cloneCall = "gene", 
                scale = TRUE)
``` 

But, I'm still running into issues with the CreateHTOContigList(). 
```r
my_list <- list(S1, S2)
contig.list <- loadContigs(input = my_list, format="BD")
sce_tcr <- createHTOContigList(contig.list, sr_obj_subset, group.by = "tissue_source")

Error in contig[contig$barcode %in% rownames(meta), ] : 
  incorrect number of dimensions
``` 

I've play with this a whole bunch and can't seem to get rid of the error. I've made sure all the cell_id's in both S1 and S2 are in the rownames(srj_obj@meta.data)) and vice versa, and tried it with both a SingleCellExp object and the Seurat object. I've also tried messing with the format of the cell ID's and it doesn't change anything. 

The cell_id's look like "PBC_12345" or "HTG_12345".  I've also tried modifying them to not include the underscore in both the contigs and the seurat object (PBC12345, HGT12345, etc), but that doesn't fix the error. 

Any help in how to resolve this would be greatly appreciated!

**Comment by kriegerm** [comment]
Update, this works!

```r
my_list <- list(S1, S2)
contig.list <- loadContigs(input = my_list, format="BD")
combined.TCR<- combineTCR(contig.list,samples = c("S1", "S2"),removeNA=TRUE)


sce <- combineExpression(combined.TCR, 
                         sr_obj, 
                         cloneCall="gene", 
                         group.by = "sample", 
                         proportion = TRUE)
``` 

But the createHTOContigList() still doesn't. Maybe that's ok though, and I can get all the functionality out of combineExpression()?

**Comment by ncborcherding** [comment]
Hey Madeline,

If you are getting things to work with the code above - don't worry about the ```createHTOContigList()```. If the experiment is multiplexed, this is really to create a contig list from a single annotation file. If you are loading multiple files and making a list, you should be ready to go. 

Nick

**Comment by kriegerm** [comment]
That's great, it's all working fantastically now! Thanks again for all your help.
